export { trainingService, TrainingService } from './TrainingService'
export { exerciseService, ExerciseService } from './ExerciseService'
export { statisticsService, StatisticsService } from './StatisticsService'
export { trainingMemoService, TrainingMemoService } from './TrainingMemoService'
export { timerService, TimerService } from './TimerService'
