/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedExercisesRouteImport } from './routes/_protected/exercises'
import { Route as ProtectedLogsRouteImport } from './routes/_protected/logs'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedStatisticsRouteImport } from './routes/_protected/statistics'
import { Route as ProtectedTimersRouteImport } from './routes/_protected/timers'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedExercisesRoute = ProtectedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLogsRoute = ProtectedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedStatisticsRoute = ProtectedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTimersRoute = ProtectedTimersRouteImport.update({
  id: '/timers',
  path: '/timers',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/exercises': typeof ProtectedExercisesRoute
  '/logs': typeof ProtectedLogsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/statistics': typeof ProtectedStatisticsRoute
  '/timers': typeof ProtectedTimersRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/exercises': typeof ProtectedExercisesRoute
  '/logs': typeof ProtectedLogsRoute
  '/settings': typeof ProtectedSettingsRoute
  '/statistics': typeof ProtectedStatisticsRoute
  '/timers': typeof ProtectedTimersRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/_protected/exercises': typeof ProtectedExercisesRoute
  '/_protected/logs': typeof ProtectedLogsRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/statistics': typeof ProtectedStatisticsRoute
  '/_protected/timers': typeof ProtectedTimersRoute
  '/api/$': typeof ApiSplatRoute
  '/api/health': typeof ApiHealthRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/offline'
    | '/exercises'
    | '/logs'
    | '/settings'
    | '/statistics'
    | '/timers'
    | '/api/$'
    | '/api/health'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/offline'
    | '/exercises'
    | '/logs'
    | '/settings'
    | '/statistics'
    | '/timers'
    | '/api/$'
    | '/api/health'
    | '/'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/offline'
    | '/_protected/exercises'
    | '/_protected/logs'
    | '/_protected/settings'
    | '/_protected/statistics'
    | '/_protected/timers'
    | '/api/$'
    | '/api/health'
    | '/_protected/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/exercises': {
      id: '/_protected/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ProtectedExercisesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/logs': {
      id: '/_protected/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof ProtectedLogsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/statistics': {
      id: '/_protected/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof ProtectedStatisticsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/timers': {
      id: '/_protected/timers'
      path: '/timers'
      fullPath: '/timers'
      preLoaderRoute: typeof ProtectedTimersRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedExercisesRoute: typeof ProtectedExercisesRoute
  ProtectedLogsRoute: typeof ProtectedLogsRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedStatisticsRoute: typeof ProtectedStatisticsRoute
  ProtectedTimersRoute: typeof ProtectedTimersRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedExercisesRoute: ProtectedExercisesRoute,
  ProtectedLogsRoute: ProtectedLogsRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedStatisticsRoute: ProtectedStatisticsRoute,
  ProtectedTimersRoute: ProtectedTimersRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
